version: '3.9'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init_docker.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: articles-api
    image: articles-api
    depends_on:
      - mysqldb
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=$DATABASE_USER
      - DB_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PORT=3306
      - DATABASE_DIALECT=$DATABASE_DIALECT
volumes: 
  db: