version: '3.9'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_ROOT_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - 3306:$DATABASE_PORT
    command: --init-file /data/application/init.sql  
    volumes:
      - ./init.sql:/data/application/init.sql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=$DATABASE_USER
      - DB_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PORT=$DATABASE_PORT
    stdin_open: true
    tty: true

volumes: 
  db: